dataset_processing:

train:
  num_epochs: 5
  classes_count: 99
  batch_size: 256
  learning_rate: 0.005
  num_data_loader_worker: 2
  alpha: 0.001
  beta: 0.1
  temperature: 1.5


paths:
  logging_path: "logs"
  model_path: "models"
  dataset_path: "data"
  teacher_weights_path: "models/MiVOLO/checkpoints/model_age_utk_4.23.pth"


